server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://118.24.207.134:3306/resume?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    view:
#      #springMVC中的视图信息，响应前缀
#      prefix: /WEB-INF/pages/
#      # 响应页面默认后缀
#      suffix: .jsp


mybatis:
  #mybatis中mapper文件的路径
  mapper-locations: classpath*:com/dengwenjin/resume/dao/mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.dengwenjin.resume.pojo

